# Generated by Django 2.2.1 on 2019-05-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_name', models.CharField(max_length=60)),
                ('Current_Shoots', models.IntegerField()),
                ('Total_Shoots', models.IntegerField()),
                ('Max_Shoots', models.IntegerField()),
                ('Status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_Name', models.CharField(max_length=60)),
                ('Name', models.CharField(max_length=60)),
                ('Status', models.IntegerField()),
                ('Current_Shoots', models.IntegerField()),
                ('Total_Shoots', models.IntegerField()),
                ('Form_Forms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Baza.Forms')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=60)),
                ('SOP_Date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Type_Id', models.CharField(max_length=60)),
                ('Project_Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Baza.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('Production_Value', models.IntegerField(default=0)),
                ('Machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Baza.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='forms',
            name='Type_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Baza.Type'),
        ),
    ]
