# Generated by Django 2.2.1 on 2019-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Baza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='shift_date',
            field=models.DateField(auto_now=True),
        ),
    ]
