# Generated by Django 2.2.1 on 2019-05-09 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Baza', '0002_auto_20190509_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='Current_Shoots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Status',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Total_Shoots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='production',
            name='Machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Baza.Machine'),
        ),
        migrations.AlterField(
            model_name='production',
            name='shift_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
