# Generated by Django 2.2.1 on 2019-05-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Baza', '0003_auto_20190509_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='Machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Baza.Machine'),
        ),
    ]
