# Generated by Django 2.2.1 on 2019-05-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Baza', '0004_auto_20190509_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_Nr', models.CharField(max_length=7)),
                ('year_in_school', models.CharField(choices=[('USR', 'USER'), ('MNX', 'MNX'), ('SVR', 'SUPERVISOR'), ('ADM', 'ADMIN')], default='USR', max_length=3)),
            ],
        ),
    ]
