# Generated by Django 2.2.1 on 2019-05-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Baza', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='year_in_school',
            new_name='User_Level',
        ),
    ]
